### ISSUE TITLE
Replace the logo in the website footer

### ISSUE THREAD

**Issue by erickzli** [I-GUIDE/ucgis-living-textbook#16]
This feature improvement is related to Issue #3. After a conversation with Robert, we clarified that the LTB logo shouldn't have been changed, but the ITC and UT logos.

Work list:
- Bring back the LTB logo;
- Update the footer logos.

**Comment by erickzli** [comment]
![Screenshot 2023-06-22 at 10 50 34 AM](https://github.com/I-GUIDE/ucgis-living-textbook/assets/17897676/e7a3d004-8acb-43a5-be0d-12b6046b6713)

Screenshot showing the current website

**Comment by erickzli** [comment]
![Screenshot 2023-06-26 at 1 09 30 PM](https://github.com/I-GUIDE/ucgis-living-textbook/assets/17897676/2d94e79f-c337-40a4-b63a-af268d712831)

Screenshot showing the updated logo.

**Comment by robertohuru** [comment]
@erickzli this is good
