### ISSUE TITLE
Bugs when there are more than one study area and users need to select one

### ISSUE THREAD

**Issue by erickzli** [I-GUIDE/ucgis-living-textbook#31]
When there are more than one study area and users need to select one, if they click open dashboard, the page will be redirected to localhost.

**Comment by robertohuru** [comment]
@erickzli 

https://github.com/I-GUIDE/ucgis-living-textbook/blob/a286ebef8af4d8371bba206b89c8771a2ecdab68/docker/ltb_prod.env.dist#L1C11-L1C11
